---
title: "Shortliffe Readings"
output:
  html_document:
    toc: true
    theme: united
    toc_depth: 2
---

---

# Chapter 1 [Text](http://bit.ly/1yN9sZq)

## informatics revolution comes to medicine
## integrated access to clinical information
## beyond the paper record
## EHRs for the future
## implications for the internet
## U.S government steps in
## biomedical informatics as basic science

---

# Chapter 2 [Text](http://bit.ly/1wdtWsc)

## biomedical data, storage and use
## clinical data
## uses of data
## collection of data
## hypothetico-deductive approach

---

# Chapter 3 [Text](http://bit.ly/1yN9JM9)

## biomedical decision making, probabilistic clinical reasoning
## uncertainty in diagnosis
## decision making
## subjective probability assessment
## measurement of operating characteristics
## specificity, sensitivity
## test performance
## bias
## bayes theorem
## markov models


---

# Chapter 4 [Text](http://bit.ly/1wdufmW)

---

# Chapter 5 [Text](http://bit.ly/1yN9X5S)

## hardware
* CPU, GPU
    * bit storage
    * binary code
    * unicode
* memory, storage, input/output
    * bytes, MB, TB
    * RAM/ROM
    * mouse, trackpad
    * LCD, LED, printers
* communication, data buses
    * images, telephone, integrated services
    * internet, frame relay, WAN, LAN, ATM
    * protocols, packets
* parallel processing

## data acquisition
* real time sampling
* filtering algorithms reduce noise
* shielding of cables

## internet communication
* TCP/IP
* ICANN
* internet address
* domain name system
* ISP, internet service provider
* network access provider

## programming languages
* we know this stuff

## data management operating systems
* application programs
* database management systems
* more stuff on networks

---

# Chapter 6 [Text](http://bit.ly/1yNaXXB)

## software in healthcare
* electronic health records
* patient portals
* health information exchange

## software functions
1. acquiring and storing data
2. summarizing and displaying data
3. facilitating communication and information
exchange
4. generating alerts, reminders, and other forms
of decision support
5. supporting educational, research, and public
health initiatives
6. software designed around care requirements

## communication of data
* summarizing
* statistics
* alerts
* CPOE
* decision support
* public health surveillance

## integrating and testing
* disruptive technology and innovation
* waterfall vs agile methods

## meaningful use
* integrated delivery systems
* laboratory information
* pharmacy information
* radiology information

## systems
* custom systems on top of commercial systems
* software as a service
* cloud computing
* HTTP, XML languages, HL7 standards

---

# Chapter 7 [Text](http://bit.ly/1GgnC5M)

## need and early use of standards
* standards developmental organizations (HL7, EDFACT, ASC X12N)
* need for patient recognition across systems
* deidentification is a pretty big issue

## settings where standards are needed
* methods of transfer are needed
* security is also needed

## standards development process
* what must it do?
* scope of it?
* gap-standards are also needed
* need dedicated volunteers over years
* open standards development policy
* several paths to maturity
* start with a draft standard for trial use, implemented by some vendors

## data standards organizations
* ISO technical committees, advisory group to determine overall standards
* CEN, European committee for standardization, develops standards for healthcare informatics
* pg. 242 list of standards organizations
* HL7 was founded to exchange clinical data
* IHE, integrating health care enterprise is to stimulate the production of health care information resources
* ASTM, American society for testing and materials, development of standards for performance materials

## structure and coded data
* standards ignored all too often
* SNOMED-CT should be used, removes the ambiguity that exists if the list of codes is used as a representation of findings
* pre-coordination and post-coordination, different ways of measurement
* pg. 247 detailed clinical models
* abstraction and classification to lable data
* representation to extract as much as possible
* DRG codes and ICD-9

## mental and nursing terminology, radiology terms
* pg. 250-257

## data interchange factors
* meta-tagging elements
* position based syntax

## HL7
* trigger model, defined for various trigger events
* clinical document architecture standard hs become globally adopted for a broad range of use.
* FHIR (fast health care interoperability resources), overcome the complexity of development based on the HL7 reference model
* based on reference information model (RIM)

## future direction
* use of data by multiple stakeholders
* expansion of types of data to be included in the EHR
* mobile health
* planning of systems, usability standards, and standards in general
* privacy and security will also be difficult
* just the beginning

---

# Chapter 8 [Text](http://bit.ly/1yNb05W)

## natural language processing
* display information in text with high validity and reliability
* knowledge discovery across articles, forums, text
* reviewing the patient chart
* aggregate and consolidate information across notes and reports
* bridge the gap between unstructured text and data by transforming the text to data

## NLP
* processing of unstructured text, minimal linguistic knowledge, based solely on the presnce of words in the text
* bag of words, key word approach
* machine learning method that uses words independently of each other
* discrete symbols (words)
* grammar (rules)
* represent this in a logical format

## applications
* question answering
* information extraction and retrieval
* relations among named entities
* modifiers of interest
* text summarization
* text generation
* machine translation
* sentiment analysis and emotion detection
* semantic relations

## techniques
* tokenization 
* low-level text processing
* character encoding
* document structure (ASCII)
* syntactic parsing and chunking
* semantic analysis, interpretation assigned to individual words, combined into larger semantic structures
* word sense interpretation
* interpretation of relations among words

## challenges
* implicit challenges
* system interoperability
* misspellings and typographical errors
* domain specific characteristics in the lexicon, subdomains too
* complex and dynamic language in biology and medicine
* polysemy, names that are the same but represent something different
* expressiveness vs ease of access
* reliance on medical knowledge and reasoning

---

# Chapter 12 [Text](http://bit.ly/1yNbJ71)

## electronic health record
* repository of electronically maintained information about individual status and health care
* legibility, accessibility, validity checks, comprehensiveness of information, use and retention of data, structure of data
* meaningful use requires LOINC, SNOMED-CT standards

## five functional components
* integrated view of patient data
* clinician order entry
* clinical decision support
* access to knowledge resources
* integrated communication and reporting support

## clinician order entry
* point of care entry
* improve healthcare
* alerts and information input

## clinical decision support
* improves care process
* identify patients who are not reaching treatment targets
* past due for immunizations
* schedule an appointment
* convenient point to offer reminders about tests or treatments
* reminder alerts in outpatient settings

## access to knowledge resources
* links to PubMed, MedlinePlus, CDC
* Infobuttons present information to the clinician on the fly

## issues
* data capture, interfacing from systems or manual data entry
* how to consolidate many different sources of data
* manual data entry may be misleading or incorrect
* physician entered data must be commented
* should the entries be free text or should they be coded?
* NLP may help with automatic encoding of narrative text
* dictation with transcription is common as well
* speech recognition as a alternative

## data validation
* validity checks must be implemented
* range checks can also be implemented
* pattern checks, data has pattern
* computed checks, values have correct mathematical relationship
* consistency checks, detect errors by comparing entered data
* delta checks, large and unlikely differences
* spelling checks

## data display
* deployment to PC or smart devices
* timeline graphs
* timeline flowsheets
* summaries and snapshots
* dynamic search function
* query and surveillance systems

## challenges ahead
* usability
* standards
* user information
* user control
* privacy and security
* costs and benefits
* leadership

---

# Chapter 13 [Text](http://bit.ly/1srgoLG)

## health information infrastructure
## vision and benefits
## ensuring information in electronic form
## financial sustainability
## compliance with standards

---

# Chapter 14 [Text](http://bit.ly/1GgnSBQ)

## management of information in healthcare organizations
## governance
## care delivery and governance
## clinical decision support
## departmental systems

---

# Chapter 15 [Text](http://bit.ly/1GgnR0N)

## patient centered care systems
## emergence
## management
## delivery system
## outlook for the future

---

# Chapter 16 [Text](http://bit.ly/1GgnWS1)

## public health informatics

---

# Chapter 17 [Text](http://bit.ly/1Ggokjl)

## consumer health informatics and personal health records
## portals
## privacy
## communication

---

# Chapter 22 [Text](http://bit.ly/1yNbuJ3)

## clincial decision support systems
## nature of decision making
## physician needs
## principles of CDS system design
## data validation
## workflow

---

# Chapter 24 [Text](http://bit.ly/1Ggok2X)

## bioinformatics
## gene sequencing
## implications for clinical informatics
## structures in biology
## sequences in biology
## genome sequencing in biology
## curse of dimensionality
## structure databases

---

# Chapter 25 [Text](http://bit.ly/1GgolE5)

## translational bioinformatics
## differences from traditional informatics
## data storage
## translational bioinformatics
## classification and prediction
## pharmacogenomics

---

# Chapter 26 [Text](http://bit.ly/1yNbyZt)

## clinical research includes
* patient-oriented mechanisms of human disease
* epi studies
* outcomes research

## clinical research informatics
* evaluation and modeling of clinical research workflow
* designing optimal human-computer interaction models
* improving information capture
* enhancing analysis and dissemination

## types of experiments
* RCT
* quasi-experiment

## clinical phases
* I, evaluation in a small group of participants
* II, evaluation in a larger group of participants
* III, even larger group of participants, RCT design
* IV, performance and safety of novel therapy after it is approved

## phases
* preparatory
* active
* dissemination

## information needs and systems
* electronic health records
* bibliographic data bases
* data warehouses
* CDSS
* feasibility analysis applications and data simulation

## reporting requirements and standards
* common language
* interlinked management

---

#Chapter 27 [Text](http://bit.ly/1yNbAAz)

## policy
* meaningful use
* hopefully health IT will live up to its goals
* integration into ACOs

## patient-centric focus
* personal health records
* telehealth
* emerging dichotomy of minority groups

## reducing costs
* EHRs can reduce costs
* use health IT to measure quality
* improve quality measurements
* improve outcome measurements

## adoption
* must increase adoption rate of EHRs
* new payment models of ACOs can accelerate health IT adoption
* need federal government oversight

## security
* regulate privacy
* instill unique health identifiers
* development of new technologies

---

# Chapter 28 [Text](http://bit.ly/1GgogA4)

## future of informatics in biomedicine
## trend one, biomedical research and clinical care, computationally linked
## trend two, information is individualized
## trend three, society is more online and collaborative
## trend four, EHRs are changing healthcare
## trend five, data is massive
## personalized health

---